version: 2
jobs:
  build:
    docker:
      - image: node:9.8.0
    steps:
      - checkout
      - run: npm install
      - run: npm install -g gulp
      - run: gulp
  test:
    docker:
      - image: node:4.2
    steps:
      - checkout
      - run: npm install
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
